export const services = [
  {
    id: 'website-design',
    number: '01',
    name: 'Website Design',
    shortDesc: 'Custom websites designed around the brand, audience and business goals.',
    description: 'Create modern, responsive and conversion-focused websites designed around the brand, audience and business goals. Every detail — from layout to interaction — is intentionally crafted to communicate your brand story and convert visitors into customers.',
    includes: [
      'Custom visual direction',
      'Responsive design',
      'Desktop + tablet + mobile layouts',
      'Conversion-focused page structure',
      'Interactive elements',
      'Modern animations',
      'Contact / CTA integration',
      'Performance-conscious implementation',
    ],
    bestFor: 'Businesses, personal brands, agencies and creators who need a complete professional website.',
    cta: 'START A WEBSITE PROJECT',
  },
  {
    id: 'landing-pages',
    number: '02',
    name: 'Landing Pages',
    shortDesc: 'Focused landing pages designed to turn visitors into action.',
    description: 'Create focused landing pages designed around one goal — turning visitors into action. Every section, headline and CTA is strategically placed to maximize engagement and drive conversions.',
    includes: [
      'Strong visual hierarchy',
      'Conversion-focused sections',
      'CTA optimization',
      'Responsive design',
      'Fast-loading layout',
      'Forms / contact integration',
      'Analytics-ready structure',
      'Smooth interactions',
    ],
    bestFor: 'Campaigns, products, services, ads and launches.',
    cta: 'START A LANDING PAGE',
  },
  {
    id: 'business-websites',
    number: '03',
    name: 'Business Websites',
    shortDesc: 'Professional websites that build trust and make it easy for customers to contact a business.',
    description: 'Build a professional online presence that makes a business look trustworthy and makes it easy for customers to take action. From homepage to contact page, every element is designed to build credibility and generate enquiries.',
    includes: [
      'Custom homepage',
      'About section',
      'Services showcase',
      'Contact integration',
      'WhatsApp integration',
      'Mobile responsive design',
      'Google-friendly structure',
      'Strong CTA placement',
    ],
    bestFor: 'Local businesses, service businesses, startups and growing brands.',
    cta: 'BUILD MY BUSINESS WEBSITE',
  },
  {
    id: 'ecommerce',
    number: '04',
    name: 'E-Commerce',
    shortDesc: 'Beautiful, intuitive shopping experiences designed around products and conversion.',
    description: 'Create a polished shopping experience designed to make browsing products and purchasing simple. Every touchpoint — from product discovery to checkout — is optimized for conversion.',
    includes: [
      'Product-focused design',
      'Category structure',
      'Product pages',
      'Cart experience',
      'Checkout flow',
      'Mobile-first experience',
      'Trust-building sections',
      'Conversion-focused UI',
    ],
    bestFor: 'Brands and businesses selling products online.',
    cta: 'START AN E-COMMERCE PROJECT',
  },
  {
    id: 'ui-ux',
    number: '05',
    name: 'UI / UX',
    shortDesc: 'Thoughtful interfaces, user flows and experiences for websites and digital products.',
    description: 'Design interfaces that are beautiful, intuitive and easy to use. Every flow, interaction and visual decision is grounded in user research and designed to create seamless digital experiences.',
    includes: [
      'User flows',
      'Information architecture',
      'Wireframes',
      'High-fidelity UI',
      'Responsive layouts',
      'Interaction design',
      'Prototyping',
      'Design systems',
    ],
    bestFor: 'Websites, web apps, dashboards, SaaS products and digital products.',
    cta: 'START A UI/UX PROJECT',
  },
  {
    id: 'website-redesign',
    number: '06',
    name: 'Website Redesign',
    shortDesc: 'Modern redesigns that improve visual quality, usability and conversion.',
    description: 'Turn an outdated or underperforming website into a modern, premium digital experience. Every improvement is focused on visual quality, usability and conversion performance.',
    includes: [
      'Existing website analysis',
      'UX improvements',
      'Visual redesign',
      'Better content hierarchy',
      'Mobile optimization',
      'Improved CTA placement',
      'Modern interactions',
      'Conversion-focused improvements',
    ],
    bestFor: 'Businesses that already have a website but feel it looks outdated, confusing or fails to convert visitors.',
    cta: 'REDESIGN MY WEBSITE',
  },
];

export function getServiceBySlug(slug) {
  return services.find(s => s.id === slug);
}
